---
title: "Anderson Hitoshi Uyekita"
output:
  html_document:
    toc: true
    toc_float: true
---
<!--- Meus estilos --->
<!--- TO DO: Inserir num arquivo CSS --->
<style>
div.t20 {
    font-size: 20px;
}

div.t20_2 {
    font-size: 20px;
}


div.t18 {
    font-size: 18px;
}

body {text-align: justify}

h1, .h1, h2, .h2, h3, .h3 {
    margin-top: 5px;
}

h1, .h1, h2, .h2, h3, .h3 {
    margin-bottom: 15px;
}

.t20 {
    margin-bottom: 10px;
}

div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}

</style>

<!--- Dados pessoais --->

<i class="fas fa-map-marker-alt"></i>  Rua dos Buritis, 437, Ap 14, Jabaquara, S&atilde;o Paulo, Brazil  
<i class="fas fa-envelope"></i>  anderson.uyekita[at]gmail.com  
<i class="fab fa-whatsapp"></i>  + 55 11 9886 4470  
<i class="fab fa-github"></i> http://github.com/AndersonUyekita  
<i class="fab fa-linkedin"></i> https://www.linkedin.com/in/andersonuyekita/  

****

<!--- Personal Statement --->

# <i class="fas fa-user-circle"></i> Personal Statement

Since I had resigned my last job position as a General Manager, I decided to move to my parent's ranch, whereby I have enjoyed a great time becoming closest to my family, learning Japanese, aiding the local community, keeping contact with nature and slowing down my pace. After a sabbatical period of 10 months, I have redesigned my long-term personal objective: a well-balanced lifestyle.

Now, I am keen to have a bit of challenge, and also to develop a solid career in an excellent company, open-minded, and with great potential to grow.

As a researcher, I have learned and taken this principle into my life:

> In some algorithms, the mutation operator is essential to introduce a new gene variety, which is crucial to surpass difficulties in a homogeneous population.

****
<!--- Experiencia Profissional --->

# <i class="fas fa-briefcase"></i> Work Experience

<div align="right">
## 5&agrave;sec  
</div>

<div class = "row">
  
<div class = "col-md-4">
<div class = "t20">5&agrave;sec  </div>
<div class = "t18">Asunci&oacute;n, Paraguay  </div>
Oct 2016 - Jan 2018  
<a href="http://www.5asec.com.py" target="blank">http://www.5asec.com.py</a>

</div>
  
<div class = "col-md-8">

<!--- 5asec Gerente Geral --->

<div class="t20">Gerente General</div>

In this job position, I have assumed the management of a local company acquired by 5&agrave;sec, which was the owner of 7 dry cleaning store. I focused my efforts on these outlets because the original 5&agrave;sec store already had skilled employees to run the business.

I have assessed these stores to create an analysis, which allowed me to study and discern how to proceed. I identified a low Gross Margin of 36%, due to an overstaffed payroll. So, I decided to downsize the staff to raise the company health.  As a result of this decision, I boosted the Gross Margin to 56,75%.

Another problem was the unprofitable commercial points due to high rents, logistics, and overheads. For this reason, I also decided to downsize the stores' number, and the result of this action was an SG&A decreasing from 23,69% to 15,81%.

As a result of my decisions, the EBITDA Margin raises from 12,24% in  2016 and reach 40,94% in 2017, even more, the revenue had increased 5,10% in this same period due to a well-trained staff. Consequently, I revamp 3 (three) stores and rebrand to 5&agrave;sec from this savings.

**Responsibilities**

* Project Management: Overseeing the revamp of old stores works and keeping it on time.
* HR Management: Employee Record, Payroll, Hiring, Training and Evaluating.
* Accounting Management: Tracking the Accounts Payables and Receivables, Economic Analysis, Reducing the SG&A costs.
* Supply Chain: Developing Local suppliers, Machinery and Consumables Importation, and Inventory control.
 Operational Management: Quality Management, Productivity Evaluation, Process Enhancement, Planning, Organizing, Supervising the production area, Logistic, and Reducing the COGS.
* Legal Issues: Business License, Environmental License, Municipal Taxes, etc.
* Technical Support and Assistance.

</div>

</div>

<div class = "row">
  
<div class = "col-md-4">
<div class = "t20">5&agrave;sec  </div>
<div class = "t18">Asunci&oacute;n, Paraguay  </div>
Jun 2016 - Oct 2016

</div>
  
<div class = "col-md-8">

<div class="t20">Operations Manager</div>

My objective in the store's beginning was to compound a good team as soon as possible. As an outcome of my commitment, I have assumed the franchise operations management, some HR's activities, and a close relationship with the accountant.

As a foreign, I was obligated to start to study the local accounting and administration to understand the Paraguayan's tributary system and the local labour law. 

**Responsibilities**

* HR Management: Hiring, Training, Evaluating, Payroll, and the Employee record.
* Operational Management: Quality Management, Productivity Evaluation, Process Enhancement, Planning, Organizing and Supervising the production area.
* Accounting Management: Tracking the Accounts Payables and Receivables.
* Legal Issues: Business License, Environmental License, Municipal Taxes,
etc.

</div>
  
</div>

<div class = "row">
  
<div class = "col-md-4">
<div class = "t20">5&agrave;sec  </div>
<div class = "t18">Asunci&oacute;n, Paraguay  </div>
Jan 2016 - Jun 2016

</div>
  
<div class = "col-md-8">

<div class="t20">Project Manager</div>

In this full-time job, I was the person in charge to introduce the 5&agrave;sec brand in Paraguay. My activities in this first moment were to oversee the works premises located in a Shopping Mall and to ensure the store's specifications preconized by the Franchise. Whilst the construction, I had been training in Madrid and Genebra stores to become the specialist in dry cleaning and laundry for 1-month.

After my formation, I have trained all my team and installed the machinery to be ready for the store roll-out (23 May 2016).

**Responsibilities**

* Project Management: Overseeing the premises construction and ensure the deadline.
* Supply Chain: Developing Local suppliers, Inventory Control, Machinery and Consumables Importation.

</div>
  
</div>

<div align="right">
## Daimon  
</div>

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">Daimon  </div>
S&atilde;o Paulo, Brazil  
Mar 2009 - Jan 2016  
<a href="http://www.daimon.com.br/usa.html" target="blank">http://www.daimon.com.br</a>
</div>
  
<div class = "col-md-8">

<!--- Daimon Engenheiro Eletricista --->

<div class="t20">Electrical Engineer</div>

As an Electrical Engineer, I have worked performing researcher and applications in R&D Projects. Due to the nature of my job, all my activities relied on learning new methods, approaches, algorithms, optimisation, statistics, mathematical modelling, etc., and later how to apply it in engineer solutions usually delivering software and technical reports.

As a consequence, my team and I have had 5 (five) papers published in the CIRED's Biennial Conferences and many other in local conferences.

I will point out the main fields of my activities in this job:

**Activities:**

* Developing a DMS's tool to aid the DSO's decision-making easier in case of programmable outages or fault.
* Developing a DSA's tool which aids the operator's decision making. This tool outcome provides an optimized place to install Capacitor Banks or/and Voltage Regulator.
* Power Flow enhancement by the use of a Load modelling and customer interviews.
* Developing a DSA's tool which allocates automatic switches.
* A proposition of an alternative method of technical losses calculation based on an evaluation of the Regulatory Agency method results.
* Creating an Action Plan to Joinville Agency (15 substations and 82 feeders) based on Network Data Analysis, Market Analysis, Forecasting growth taxes (82 feeders), Technical Economic Study, and Reliability Study.

**Responsibilities:**

* Mathematical Modelling: I was in charge of finding out a way to translate a real-life problem into a mathematical problem (Chinese Postman Problem, Set Covering, Assignment Problem, Knapsack Problem, etc.).

* Problem-Solving: After defining the mathematical problem, I have to investigate which variables are available, then set a strategy to solve it using algorithms.

* Research: My task was to search by PhD thesis, Master Dissertation, or Books which could help my team and me to find out a solution proposition, mathematical modelling, algorithms, or a new technique.

* New Projects Proposal: Keeping updated from new technologies of Power Distribution and overseeing new clients' demands to future proposals.

* Consultancy: Elaboration of Technical Studies (Reliability, Assets, Power Quality, Market, etc.) and Creating Action Plans.

* Regulatory Affairs: Application of the Regulatory method of technical losses.

* Prototyping: Testing the model and algorithms chosen to find any inconsistencies before the Development step. Sometimes, I also have programmed this prototype in R.

* Technical Report: Writing reports to the clients with an explanation of methods, algorithms, user manual, data analysis, and outcomes from the R&D projects. Also, applying paper to conferences.

* Economic Analysis: Evaluation of any action on the grid to measure the trade-off between Investment/Action and Gains (Reliability, Power Quality, etc.).

* Project Management: Keeping the expenses under control, deliverables on time, client contact to receive its feedback, and assisting the Development team.

</div>
  
</div>

****
<!--- Formacao Academica --->

# <i class="fas fa-graduation-cap"></i> Education

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">Polytechnic School of the University of S&atilde;o Paulo  </div>
<div class="t18">S&atilde;o Paulo, Brazil  </div>
2004 - 2011

<a href="https://www.poli.usp.br" target="blank">https://www.poli.usp.br</a>

</div>
  
<div class = "col-md-8">

<div class="t20">Bachelor in Electrical Engineer  </div>

* Major in Electric Distribution Systems.

Undergraduate Thesis: Development of Offshore Ocean Waves Power Generator Prototype.  

<ul class="nav nav-pills">
  <li role="presentation"><a href="/site/02-TF/TF1.pdf" target="blank">Read TF1</a></li>
  <li role="presentation"><a href="/site/02-TF/TF2.pdf" target="blank">Read TF2</a></li>
</ul>

</div>
  
</div>


##### {.tabset}

###### Courses

<!--- Cursos Presenciais na Bovespa e no FIPE --->

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">Courses  </div>
<div class="t18">S&atilde;o Paulo, Brazil  </div>
2009 - 2016

</div>

<div class = "col-md-8">

* <div class="t20_2">B3</div>
       * <div class="t18">An&aacute;lise T&eacute;cnica para o Mercado de A&ccedil;&otilde;es</div>
       * <div class="t18">Introdu&ccedil;&atilde;o ao Mercado de Renda Fixa</div>
       * <div class="t18">Mercado de A&ccedil;&otilde;es</div>
       * <a href="http://www.b3.com.br/" target="blank">http://www.b3.com.br/en_us/</a>  
<br>
* <div class="t20_2">Funda&ccedil;&atilde;o Instituto de Pesquisas Econ&ocirc;micas - Fipe</div>
       * <div class="t18">An&aacute;lise Econ&ocirc;mica, Planejamento e Gerenciamento de Projetos</div>
       * <div class="t18">An&aacute;lise de Investimentos - T&eacute;cnicas B&aacute;sicas</div>
       * <div class="t18">Econometria Aplicada</div>
       * <div class="t18">Planejamento e Gest&atilde;o de Cidades Inteligentes e Sustent&aacute;veis</div>
       * <a href="http://www.fipe.org.br" target="blank">http://www.fipe.org.br</a>

</div>
  
</div>

###### MOOCs

<!--- Cursos Coursera --->

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">Coursera  </div>
2009 - 2016  
<a href="http://www.coursera.org" target="_blank">http://www.coursera.org</a>


</div>

<div class = "col-md-8">

* <div class="t20_2">Course</div>
       * <div class="t18">An Introduction to Interactive Programming in Python (Part 2)</div>
       * <div class="t18">An Introduction to Interactive Programming in Python (Part 1)</div>
       * <div class="t18">Exploratory Data Analysis</div>
       * <div class="t18">Reproducible Research</div>
       * <div class="t18">Statistical Inference</div>
       * <div class="t18">Getting and Cleaning Data</div>
       * <div class="t18">R Programming</div>
       * <div class="t18">The Data Scientist’s Toolbox</div>
</div>
  
</div>

<!--- Cursos EdX --->

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">EdX  </div>
2009 - 2016  
<a href="https://www.edx.org" target="_blank">https://www.edx.org</a>

</div>

<div class = "col-md-8">

* <div class="t20_2">Course</div>
       * <div class="t18">Introduction to Project Management</div>
       * <div class="t18">Inclusive Leadership Training: Get Beyond Work-Life Balance</div>
       * <div class="t18">Introduction to Computer Science and Programming Using Python</div>
       * <div class="t18">Explore Statistics with R</div>
</div>
  
</div>

<!--- Cursos DataCamp --->

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">DataCamp  </div>
2009 - 2016  
<a href="https://www.datacamp.com" target="_blank">https://www.datacamp.com</a>

</div>

<div class = "col-md-8">

* <div class="t20_2">Course</div>
       * <div class="t18">Intermediate R</div>
       * <div class="t18">Reporting with R Markdown</div>
       * <div class="t18">Introduction to R</div>
</div>
  
</div>

##### {.end}
****
<!--- Habilidade Tecnicas - Hard Skills --->

# <i class="fas fa-chart-bar"></i> Technical Skills

<div class = "row">
  
<div class = "col-md-6">

* R Language.
* Project Management.
* DSA (Distribution System Analysis), DMS (Distribution Management System) and OMS (Outage Management System).
* Mathematical Modeling, Optimisation, Econometrics, Data Analysis, and Forecasting.
* Technical Economic Studies.


</div>
  
<div class = "col-md-6">

* Management and Accounting.
* Planning and Operational the Electrical Distribution Systems.
* Knowledge Management.
* Network Optimization.
* Regulatory Affairs.

</div>
  
</div>

****
<!--- Caracteristicas comportamentais - Soft Skills --->

# <i class="fas fa-users"></i> Personal Skills

* Collaborative Mindset: In 5&agrave;sec, I have tried to put a skilled employees to mentor the newcomers, which developed empathy among team member, as a consequence, they start to share knowledge and arranging solutions. I also detected the leaders whom I promoted.

* Commitment: The ownership mentality, responsibility, sense of belonging, personal involvement, and ethics are part of the commitment. When I applied it to 5&agrave;sec, I observed an increase in production. So I will encourage my team to do the same.

* Holistic Approach: I always keep in mind the decisions' consequences on the global view, because a myopic approach could hinder the problem's understood. For this reason, I investigate the problem through a broader horizon before any decision.

* Adaptability: In my work history, I have already worked as Electrical Engineer, Programmer, Researcher, Ironer, Receptionist, Choffer, General Manager, etc.

* Willingness to Learn: Based on my activities in R&D, I am used to learning by myself, that is why I usually enrol on Coursera and EdX courses. I also received the technical support training in Italy in June 2017.

* Communication: As an engineer, I have presented technical papers in conferences, technical presentation (about methodologies, algorithms, etc.), and I have trained clients to use DSA and DMS software. I also worked at 5&agrave;sec stores on the counter as a receptionist.

****
<!--- Trabalho Voluntario --->

# <i class="fas fa-people-carry"></i> Volunteer Activities

<div class = "row">
  
<div class = "col-md-4">
<div class="t20">Volunteer  </div>
<div class="t18">Mogi das Cruzes, Brazil  </div>
Apr 2018

</div>
  
<div class = "col-md-8">

<div class="t20">Akimatsuri 2018  </div>

I was a volunteer at an event hosted by the Japanese Community from Mogi das Cruzes called Akimatsuri. I have aided the elders for 4 days (each day for 4 hours).

https://www.akimatsuri.com.br

</div>
  
</div>


<div class = "row">
  
<div class = "col-md-4">
<div class="t20">Volunteer  </div>
<div class="t18">Mogi das Cruzes, Brazil  </div>
Jan 2006 - Dec 2007

</div>
  
<div class = "col-md-8">
<div class="t20">Electrical Engineering Academic Center</div>

I was a volunteer, and I worked 20 hours a week.

**Responsibilities**

* Campi Newspapers Editor
* Academic Center Maintenance and Organization
* Event Organizer with Alumni and Students
* Technical Lecture Organizer


</div>
  
</div>


****
<!--- Conquistas --->

# <i class="fas fa-trophy"></i> Achievements

* 5àsec Best Starter

****
<!--- Publicacoes --->

# <i class="far fa-newspaper"></i> Publications

* Medium voltage planning tool based on utilities best practices and multi-objective optimization

* Losses Forecast using Econometric Models <a href="/site/01-Publications/CIRED2015_0255_final.pdf" target="_blank"><i class="fas fa-book-reader"></i></a>

* MV planning approach using time series, billing data of medium voltage consumers and substation feeders metering <a href="/site/01-Publications/CIRED2015_0544_final.pdf" target="_blank"><i class="fas fa-book-reader"></i></a>

* Technical Losses Calculation using Simplified Models for Regulatory Purposes <a href="/site/01-Publications/CIRED2015_1197_final.pdf" target="_blank"><i class="fas fa-book-reader"></i></a>

* Load modeling based on field survey of electric appliances ownership and consumption habits <a href="/site/01-Publications/CIRED2013_0884_final.pdf" target="_blank"><i class="fas fa-book-reader"></i></a>

* Optimized switching using heuristic algorithm to support the restoration of distribution systems <a href="/site/01-Publications/CIRED2013_0879_final.pdf" target="_blank"><i class="fas fa-book-reader"></i></a>


***
<!--- Interesses --->

# <i class="fas fa-plus-circle"></i>Interests

* Well-balanced Lifestyle
* Smart-grid: I want to learn more about it.
* Distributed Generation and Micro-grid
* Management and Accounting
* Learn Japanese: To keep my ancestry culture.
* Next Book: Mindset - The New Psychology of Success (2006, Carol Dweck)
* I want to finish the Data Science Specialization on Coursera
